struct ELEMENT 
{
	CK_ULONG eleValue;
	char *eleName;
};

struct ELEMENT MECHANISM_LIST[] =
{
	{CKM_RSA_PKCS_KEY_PAIR_GEN, "CKM_RSA_PKCS_KEY_PAIR_GEN"},
	{CKM_RSA_PKCS, "CKM_RSA_PKCS"},
	{CKM_RSA_9796, "CKM_RSA_9796"},
	{CKM_RSA_X_509, "CKM_RSA_X_509"},
	{CKM_MD2_RSA_PKCS, "CKM_MD2_RSA_PKCS"},
	{CKM_MD5_RSA_PKCS, "CKM_MD5_RSA_PKCS"},
	{CKM_SHA1_RSA_PKCS, "CKM_SHA1_RSA_PKCS"},
	{CKM_RIPEMD128_RSA_PKCS, "CKM_RIPEMD128_RSA_PKCS"},
	{CKM_RIPEMD160_RSA_PKCS, "CKM_RIPEMD160_RSA_PKCS"},
	{CKM_RSA_PKCS_OAEP, "CKM_RSA_PKCS_OAEP"},
	{CKM_RSA_X9_31_KEY_PAIR_GEN, "CKM_RSA_X9_31_KEY_PAIR_GEN"},
	{CKM_RSA_X9_31, "CKM_RSA_X9_31"},
	{CKM_SHA1_RSA_X9_31, "CKM_SHA1_RSA_X9_31"},
	{CKM_RSA_PKCS_PSS, "CKM_RSA_PKCS_PSS"},
	{CKM_SHA1_RSA_PKCS_PSS, "CKM_SHA1_RSA_PKCS_PSS"},
	{CKM_DSA_KEY_PAIR_GEN, "CKM_DSA_KEY_PAIR_GEN"},
	{CKM_DSA, "CKM_DSA"},
	{CKM_DSA_SHA1, "CKM_DSA_SHA1"},
	{CKM_DH_PKCS_KEY_PAIR_GEN, "CKM_DH_PKCS_KEY_PAIR_GEN"},
	{CKM_DH_PKCS_DERIVE, "CKM_DH_PKCS_DERIVE"},
	{CKM_X9_42_DH_KEY_PAIR_GEN, "CKM_X9_42_DH_KEY_PAIR_GEN"},
	{CKM_X9_42_DH_DERIVE, "CKM_X9_42_DH_DERIVE"},
	{CKM_X9_42_DH_HYBRID_DERIVE, "CKM_X9_42_DH_HYBRID_DERIVE"},
	{CKM_X9_42_MQV_DERIVE, "CKM_X9_42_MQV_DERIVE"},
	{CKM_SHA256_RSA_PKCS, "CKM_SHA256_RSA_PKCS"},
	{CKM_SHA384_RSA_PKCS, "CKM_SHA384_RSA_PKCS"},
	{CKM_SHA512_RSA_PKCS, "CKM_SHA512_RSA_PKCS"},
	{CKM_SHA256_RSA_PKCS_PSS, "CKM_SHA256_RSA_PKCS_PSS"},
	{CKM_SHA384_RSA_PKCS_PSS, "CKM_SHA384_RSA_PKCS_PSS"},
	{CKM_SHA512_RSA_PKCS_PSS, "CKM_SHA512_RSA_PKCS_PSS"},
	{CKM_SHA224_RSA_PKCS, "CKM_SHA224_RSA_PKCS"},
	{CKM_SHA224_RSA_PKCS_PSS, "CKM_SHA224_RSA_PKCS_PSS"},
	{CKM_RC2_KEY_GEN, "CKM_RC2_KEY_GEN"},
	{CKM_RC2_ECB, "CKM_RC2_ECB"},
	{CKM_RC2_CBC, "CKM_RC2_CBC"},
	{CKM_RC2_MAC, "CKM_RC2_MAC"},
	{CKM_RC2_MAC_GENERAL, "CKM_RC2_MAC_GENERAL"},
	{CKM_RC2_CBC_PAD, "CKM_RC2_CBC_PAD"},
	{CKM_RC4_KEY_GEN, "CKM_RC4_KEY_GEN"},
	{CKM_RC4, "CKM_RC4"},
	{CKM_DES_KEY_GEN, "CKM_DES_KEY_GEN"},
	{CKM_DES_ECB, "CKM_DES_ECB"},
	{CKM_DES_CBC, "CKM_DES_CBC"},
	{CKM_DES_MAC, "CKM_DES_MAC"},
	{CKM_DES_MAC_GENERAL, "CKM_DES_MAC_GENERAL"},
	{CKM_DES_CBC_PAD, "CKM_DES_CBC_PAD"},
	{CKM_DES2_KEY_GEN, "CKM_DES2_KEY_GEN"},
	{CKM_DES3_KEY_GEN, "CKM_DES3_KEY_GEN"},
	{CKM_DES3_ECB, "CKM_DES3_ECB"},
	{CKM_DES3_CBC, "CKM_DES3_CBC"},
	{CKM_DES3_MAC, "CKM_DES3_MAC"},
	{CKM_DES3_MAC_GENERAL, "CKM_DES3_MAC_GENERAL"},
	{CKM_DES3_CBC_PAD, "CKM_DES3_CBC_PAD"},
	{CKM_CDMF_KEY_GEN, "CKM_CDMF_KEY_GEN"},
	{CKM_CDMF_ECB, "CKM_CDMF_ECB"},
	{CKM_CDMF_CBC, "CKM_CDMF_CBC"},
	{CKM_CDMF_MAC, "CKM_CDMF_MAC"},
	{CKM_CDMF_MAC_GENERAL, "CKM_CDMF_MAC_GENERAL"},
	{CKM_CDMF_CBC_PAD, "CKM_CDMF_CBC_PAD"},
	{CKM_DES_OFB64, "CKM_DES_OFB64"},
	{CKM_DES_OFB8, "CKM_DES_OFB8"},
	{CKM_DES_CFB64, "CKM_DES_CFB64"},
	{CKM_DES_CFB8, "CKM_DES_CFB8"},
	{CKM_MD2, "CKM_MD2"},
	{CKM_MD2_HMAC, "CKM_MD2_HMAC"},
	{CKM_MD2_HMAC_GENERAL, "CKM_MD2_HMAC_GENERAL"},
	{CKM_MD5, "CKM_MD5"},
	{CKM_MD5_HMAC, "CKM_MD5_HMAC"},
	{CKM_MD5_HMAC_GENERAL, "CKM_MD5_HMAC_GENERAL"},
	{CKM_SHA_1, "CKM_SHA_1"},
	{CKM_SHA_1_HMAC, "CKM_SHA_1_HMAC"},
	{CKM_SHA_1_HMAC_GENERAL, "CKM_SHA_1_HMAC_GENERAL"},
	{CKM_RIPEMD128, "CKM_RIPEMD128"},
	{CKM_RIPEMD128_HMAC, "CKM_RIPEMD128_HMAC"},
	{CKM_RIPEMD128_HMAC_GENERAL, "CKM_RIPEMD128_HMAC_GENERAL"},
	{CKM_RIPEMD160, "CKM_RIPEMD160"},
	{CKM_RIPEMD160_HMAC, "CKM_RIPEMD160_HMAC"},
	{CKM_RIPEMD160_HMAC_GENERAL, "CKM_RIPEMD160_HMAC_GENERAL"},
	{CKM_SHA256, "CKM_SHA256"},
	{CKM_SHA256_HMAC, "CKM_SHA256_HMAC"},
	{CKM_SHA256_HMAC_GENERAL, "CKM_SHA256_HMAC_GENERAL"},
	{CKM_SHA224, "CKM_SHA224"},
	{CKM_SHA224_HMAC, "CKM_SHA224_HMAC"},
	{CKM_SHA224_HMAC_GENERAL, "CKM_SHA224_HMAC_GENERAL"},
	{CKM_SHA384, "CKM_SHA384"},
	{CKM_SHA384_HMAC, "CKM_SHA384_HMAC"},
	{CKM_SHA384_HMAC_GENERAL, "CKM_SHA384_HMAC_GENERAL"},
	{CKM_SHA512, "CKM_SHA512"},
	{CKM_SHA512_HMAC, "CKM_SHA512_HMAC"},
	{CKM_SHA512_HMAC_GENERAL, "CKM_SHA512_HMAC_GENERAL"},
	{CKM_SECURID_KEY_GEN, "CKM_SECURID_KEY_GEN"},
	{CKM_SECURID, "CKM_SECURID"},
	{CKM_HOTP_KEY_GEN, "CKM_HOTP_KEY_GEN"},
	{CKM_HOTP, "CKM_HOTP"},
	{CKM_ACTI, "CKM_ACTI"},
	{CKM_ACTI_KEY_GEN, "CKM_ACTI_KEY_GEN"},
	{CKM_CAST_KEY_GEN, "CKM_CAST_KEY_GEN"},
	{CKM_CAST_ECB, "CKM_CAST_ECB"},
	{CKM_CAST_CBC, "CKM_CAST_CBC"},
	{CKM_CAST_MAC, "CKM_CAST_MAC"},
	{CKM_CAST_MAC_GENERAL, "CKM_CAST_MAC_GENERAL"},
	{CKM_CAST_CBC_PAD, "CKM_CAST_CBC_PAD"},
	{CKM_CAST3_KEY_GEN, "CKM_CAST3_KEY_GEN"},
	{CKM_CAST3_ECB, "CKM_CAST3_ECB"},
	{CKM_CAST3_CBC, "CKM_CAST3_CBC"},
	{CKM_CAST3_MAC, "CKM_CAST3_MAC"},
	{CKM_CAST3_MAC_GENERAL, "CKM_CAST3_MAC_GENERAL"},
	{CKM_CAST3_CBC_PAD, "CKM_CAST3_CBC_PAD"},
	{CKM_CAST5_KEY_GEN, "CKM_CAST5_KEY_GEN"},
	{CKM_CAST128_KEY_GEN, "CKM_CAST128_KEY_GEN"},
	{CKM_CAST5_ECB, "CKM_CAST5_ECB"},
	{CKM_CAST128_ECB, "CKM_CAST128_ECB"},
	{CKM_CAST5_CBC, "CKM_CAST5_CBC"},
	{CKM_CAST128_CBC, "CKM_CAST128_CBC"},
	{CKM_CAST5_MAC, "CKM_CAST5_MAC"},
	{CKM_CAST128_MAC, "CKM_CAST128_MAC"},
	{CKM_CAST5_MAC_GENERAL, "CKM_CAST5_MAC_GENERAL"},
	{CKM_CAST128_MAC_GENERAL, "CKM_CAST128_MAC_GENERAL"},
	{CKM_CAST5_CBC_PAD, "CKM_CAST5_CBC_PAD"},
	{CKM_CAST128_CBC_PAD, "CKM_CAST128_CBC_PAD"},
	{CKM_RC5_KEY_GEN, "CKM_RC5_KEY_GEN"},
	{CKM_RC5_ECB, "CKM_RC5_ECB"},
	{CKM_RC5_CBC, "CKM_RC5_CBC"},
	{CKM_RC5_MAC, "CKM_RC5_MAC"},
	{CKM_RC5_MAC_GENERAL, "CKM_RC5_MAC_GENERAL"},
	{CKM_RC5_CBC_PAD, "CKM_RC5_CBC_PAD"},
	{CKM_IDEA_KEY_GEN, "CKM_IDEA_KEY_GEN"},
	{CKM_IDEA_ECB, "CKM_IDEA_ECB"},
	{CKM_IDEA_CBC, "CKM_IDEA_CBC"},
	{CKM_IDEA_MAC, "CKM_IDEA_MAC"},
	{CKM_IDEA_MAC_GENERAL, "CKM_IDEA_MAC_GENERAL"},
	{CKM_IDEA_CBC_PAD, "CKM_IDEA_CBC_PAD"},
	{CKM_GENERIC_SECRET_KEY_GEN, "CKM_GENERIC_SECRET_KEY_GEN"},
	{CKM_CONCATENATE_BASE_AND_KEY, "CKM_CONCATENATE_BASE_AND_KEY"},
	{CKM_CONCATENATE_BASE_AND_DATA, "CKM_CONCATENATE_BASE_AND_DATA"},
	{CKM_CONCATENATE_DATA_AND_BASE, "CKM_CONCATENATE_DATA_AND_BASE"},
	{CKM_XOR_BASE_AND_DATA, "CKM_XOR_BASE_AND_DATA"},
	{CKM_EXTRACT_KEY_FROM_KEY, "CKM_EXTRACT_KEY_FROM_KEY"},
	{CKM_SSL3_PRE_MASTER_KEY_GEN, "CKM_SSL3_PRE_MASTER_KEY_GEN"},
	{CKM_SSL3_MASTER_KEY_DERIVE, "CKM_SSL3_MASTER_KEY_DERIVE"},
	{CKM_SSL3_KEY_AND_MAC_DERIVE, "CKM_SSL3_KEY_AND_MAC_DERIVE"},
	{CKM_SSL3_MASTER_KEY_DERIVE_DH, "CKM_SSL3_MASTER_KEY_DERIVE_DH"},
	{CKM_TLS_PRE_MASTER_KEY_GEN, "CKM_TLS_PRE_MASTER_KEY_GEN"},
	{CKM_TLS_MASTER_KEY_DERIVE, "CKM_TLS_MASTER_KEY_DERIVE"},
	{CKM_TLS_KEY_AND_MAC_DERIVE, "CKM_TLS_KEY_AND_MAC_DERIVE"},
	{CKM_TLS_MASTER_KEY_DERIVE_DH, "CKM_TLS_MASTER_KEY_DERIVE_DH"},
	{CKM_TLS_PRF, "CKM_TLS_PRF"},
	{CKM_SSL3_MD5_MAC, "CKM_SSL3_MD5_MAC"},
	{CKM_SSL3_SHA1_MAC, "CKM_SSL3_SHA1_MAC"},
	{CKM_MD5_KEY_DERIVATION, "CKM_MD5_KEY_DERIVATION"},
	{CKM_MD2_KEY_DERIVATION, "CKM_MD2_KEY_DERIVATION"},
	{CKM_SHA1_KEY_DERIVATION, "CKM_SHA1_KEY_DERIVATION"},
	{CKM_SHA256_KEY_DERIVATION, "CKM_SHA256_KEY_DERIVATION"},
	{CKM_SHA384_KEY_DERIVATION, "CKM_SHA384_KEY_DERIVATION"},
	{CKM_SHA512_KEY_DERIVATION, "CKM_SHA512_KEY_DERIVATION"},
	{CKM_SHA224_KEY_DERIVATION, "CKM_SHA224_KEY_DERIVATION"},
	{CKM_PBE_MD2_DES_CBC, "CKM_PBE_MD2_DES_CBC"},
	{CKM_PBE_MD5_DES_CBC, "CKM_PBE_MD5_DES_CBC"},
	{CKM_PBE_MD5_CAST_CBC, "CKM_PBE_MD5_CAST_CBC"},
	{CKM_PBE_MD5_CAST3_CBC, "CKM_PBE_MD5_CAST3_CBC"},
	{CKM_PBE_MD5_CAST5_CBC, "CKM_PBE_MD5_CAST5_CBC"},
	{CKM_PBE_MD5_CAST128_CBC, "CKM_PBE_MD5_CAST128_CBC"},
	{CKM_PBE_SHA1_CAST5_CBC, "CKM_PBE_SHA1_CAST5_CBC"},
	{CKM_PBE_SHA1_CAST128_CBC, "CKM_PBE_SHA1_CAST128_CBC"},
	{CKM_PBE_SHA1_RC4_128, "CKM_PBE_SHA1_RC4_128"},
	{CKM_PBE_SHA1_RC4_40, "CKM_PBE_SHA1_RC4_40"},
	{CKM_PBE_SHA1_DES3_EDE_CBC, "CKM_PBE_SHA1_DES3_EDE_CBC"},
	{CKM_PBE_SHA1_DES2_EDE_CBC, "CKM_PBE_SHA1_DES2_EDE_CBC"},
	{CKM_PBE_SHA1_RC2_128_CBC, "CKM_PBE_SHA1_RC2_128_CBC"},
	{CKM_PBE_SHA1_RC2_40_CBC, "CKM_PBE_SHA1_RC2_40_CBC"},
	{CKM_PKCS5_PBKD2, "CKM_PKCS5_PBKD2"},
	{CKM_PBA_SHA1_WITH_SHA1_HMAC, "CKM_PBA_SHA1_WITH_SHA1_HMAC"},
	{CKM_WTLS_PRE_MASTER_KEY_GEN, "CKM_WTLS_PRE_MASTER_KEY_GEN"},
	{CKM_WTLS_MASTER_KEY_DERIVE, "CKM_WTLS_MASTER_KEY_DERIVE"},
	{CKM_WTLS_MASTER_KEY_DERIVE_DH_ECC, "CKM_WTLS_MASTER_KEY_DERIVE_DH_ECC"},
	{CKM_WTLS_PRF, "CKM_WTLS_PRF"},
	{CKM_WTLS_SERVER_KEY_AND_MAC_DERIVE, "CKM_WTLS_SERVER_KEY_AND_MAC_DERIVE"},
	{CKM_WTLS_CLIENT_KEY_AND_MAC_DERIVE, "CKM_WTLS_CLIENT_KEY_AND_MAC_DERIVE"},
	{CKM_KEY_WRAP_LYNKS, "CKM_KEY_WRAP_LYNKS"},
	{CKM_KEY_WRAP_SET_OAEP, "CKM_KEY_WRAP_SET_OAEP"},
	{CKM_CMS_SIG, "CKM_CMS_SIG"},
	{CKM_KIP_DERIVE, "CKM_KIP_DERIVE"},
	{CKM_KIP_WRAP, "CKM_KIP_WRAP"},
	{CKM_KIP_MAC, "CKM_KIP_MAC"},
	{CKM_CAMELLIA_KEY_GEN, "CKM_CAMELLIA_KEY_GEN"},
	{CKM_CAMELLIA_ECB, "CKM_CAMELLIA_ECB"},
	{CKM_CAMELLIA_CBC, "CKM_CAMELLIA_CBC"},
	{CKM_CAMELLIA_MAC, "CKM_CAMELLIA_MAC"},
	{CKM_CAMELLIA_MAC_GENERAL, "CKM_CAMELLIA_MAC_GENERAL"},
	{CKM_CAMELLIA_CBC_PAD, "CKM_CAMELLIA_CBC_PAD"},
	{CKM_CAMELLIA_ECB_ENCRYPT_DATA, "CKM_CAMELLIA_ECB_ENCRYPT_DATA"},
	{CKM_CAMELLIA_CBC_ENCRYPT_DATA, "CKM_CAMELLIA_CBC_ENCRYPT_DATA"},
	{CKM_CAMELLIA_CTR, "CKM_CAMELLIA_CTR"},
	{CKM_ARIA_KEY_GEN, "CKM_ARIA_KEY_GEN"},
	{CKM_ARIA_ECB, "CKM_ARIA_ECB"},
	{CKM_ARIA_CBC, "CKM_ARIA_CBC"},
	{CKM_ARIA_MAC, "CKM_ARIA_MAC"},
	{CKM_ARIA_MAC_GENERAL, "CKM_ARIA_MAC_GENERAL"},
	{CKM_ARIA_CBC_PAD, "CKM_ARIA_CBC_PAD"},
	{CKM_ARIA_ECB_ENCRYPT_DATA, "CKM_ARIA_ECB_ENCRYPT_DATA"},
	{CKM_ARIA_CBC_ENCRYPT_DATA, "CKM_ARIA_CBC_ENCRYPT_DATA"},
	{CKM_SKIPJACK_KEY_GEN, "CKM_SKIPJACK_KEY_GEN"},
	{CKM_SKIPJACK_ECB64, "CKM_SKIPJACK_ECB64"},
	{CKM_SKIPJACK_CBC64, "CKM_SKIPJACK_CBC64"},
	{CKM_SKIPJACK_OFB64, "CKM_SKIPJACK_OFB64"},
	{CKM_SKIPJACK_CFB64, "CKM_SKIPJACK_CFB64"},
	{CKM_SKIPJACK_CFB32, "CKM_SKIPJACK_CFB32"},
	{CKM_SKIPJACK_CFB16, "CKM_SKIPJACK_CFB16"},
	{CKM_SKIPJACK_CFB8, "CKM_SKIPJACK_CFB8"},
	{CKM_SKIPJACK_WRAP, "CKM_SKIPJACK_WRAP"},
	{CKM_SKIPJACK_PRIVATE_WRAP, "CKM_SKIPJACK_PRIVATE_WRAP"},
	{CKM_SKIPJACK_RELAYX, "CKM_SKIPJACK_RELAYX"},
	{CKM_KEA_KEY_PAIR_GEN, "CKM_KEA_KEY_PAIR_GEN"},
	{CKM_KEA_KEY_DERIVE, "CKM_KEA_KEY_DERIVE"},
	{CKM_FORTEZZA_TIMESTAMP, "CKM_FORTEZZA_TIMESTAMP"},
	{CKM_BATON_KEY_GEN, "CKM_BATON_KEY_GEN"},
	{CKM_BATON_ECB128, "CKM_BATON_ECB128"},
	{CKM_BATON_ECB96, "CKM_BATON_ECB96"},
	{CKM_BATON_CBC128, "CKM_BATON_CBC128"},
	{CKM_BATON_COUNTER, "CKM_BATON_COUNTER"},
	{CKM_BATON_SHUFFLE, "CKM_BATON_SHUFFLE"},
	{CKM_BATON_WRAP, "CKM_BATON_WRAP"},
	{CKM_ECDSA_KEY_PAIR_GEN, "CKM_ECDSA_KEY_PAIR_GEN"},
	{CKM_EC_KEY_PAIR_GEN, "CKM_EC_KEY_PAIR_GEN"},
	{CKM_ECDSA, "CKM_ECDSA"},
	{CKM_ECDSA_SHA1, "CKM_ECDSA_SHA1"},
	{CKM_ECDH1_DERIVE, "CKM_ECDH1_DERIVE"},
	{CKM_ECDH1_COFACTOR_DERIVE, "CKM_ECDH1_COFACTOR_DERIVE"},
	{CKM_ECMQV_DERIVE, "CKM_ECMQV_DERIVE"},
	{CKM_JUNIPER_KEY_GEN, "CKM_JUNIPER_KEY_GEN"},
	{CKM_JUNIPER_ECB128, "CKM_JUNIPER_ECB128"},
	{CKM_JUNIPER_CBC128, "CKM_JUNIPER_CBC128"},
	{CKM_JUNIPER_COUNTER, "CKM_JUNIPER_COUNTER"},
	{CKM_JUNIPER_SHUFFLE, "CKM_JUNIPER_SHUFFLE"},
	{CKM_JUNIPER_WRAP, "CKM_JUNIPER_WRAP"},
	{CKM_FASTHASH, "CKM_FASTHASH"},
	{CKM_AES_KEY_GEN, "CKM_AES_KEY_GEN"},
	{CKM_AES_ECB, "CKM_AES_ECB"},
	{CKM_AES_CBC, "CKM_AES_CBC"},
	{CKM_AES_MAC, "CKM_AES_MAC"},
	{CKM_AES_MAC_GENERAL, "CKM_AES_MAC_GENERAL"},
	{CKM_AES_CBC_PAD, "CKM_AES_CBC_PAD"},
	{CKM_AES_CTR, "CKM_AES_CTR"},
	{CKM_BLOWFISH_KEY_GEN, "CKM_BLOWFISH_KEY_GEN"},
	{CKM_BLOWFISH_CBC, "CKM_BLOWFISH_CBC"},
	{CKM_TWOFISH_KEY_GEN, "CKM_TWOFISH_KEY_GEN"},
	{CKM_TWOFISH_CBC, "CKM_TWOFISH_CBC"},
	{CKM_DES_ECB_ENCRYPT_DATA, "CKM_DES_ECB_ENCRYPT_DATA"},
	{CKM_DES_CBC_ENCRYPT_DATA, "CKM_DES_CBC_ENCRYPT_DATA"},
	{CKM_DES3_ECB_ENCRYPT_DATA, "CKM_DES3_ECB_ENCRYPT_DATA"},
	{CKM_DES3_CBC_ENCRYPT_DATA, "CKM_DES3_CBC_ENCRYPT_DATA"},
	{CKM_AES_ECB_ENCRYPT_DATA, "CKM_AES_ECB_ENCRYPT_DATA"},
	{CKM_AES_CBC_ENCRYPT_DATA, "CKM_AES_CBC_ENCRYPT_DATA"},
	{CKM_DSA_PARAMETER_GEN, "CKM_DSA_PARAMETER_GEN"},
	{CKM_DH_PKCS_PARAMETER_GEN, "CKM_DH_PKCS_PARAMETER_GEN"},
	{CKM_X9_42_DH_PARAMETER_GEN, "CKM_X9_42_DH_PARAMETER_GEN"},
	{CKM_VENDOR_DEFINED, "CKM_VENDOR_DEFINED"},
	{0, NULL}
};

struct ELEMENT CK_SLOT_INFO_FLAG_LIST[] =
{
	{CKF_TOKEN_PRESENT, "CKF_TOKEN_PRESENT"},
	{CKF_REMOVABLE_DEVICE, "CKF_REMOVABLE_DEVICE"},
	{CKF_HW_SLOT, "CKF_HW_SLOT"},
	{0, NULL}
};

struct ELEMENT CK_MECHANISM_INFO_FLAG_LIST[] =
{
	{CKF_HW, "CKF_HW"},
	{CKF_ENCRYPT, "CKF_ENCRYPT"},
	{CKF_DECRYPT, "CKF_DECRYPT"},
	{CKF_DIGEST, "CKF_DIGEST"},
	{CKF_SIGN, "CKF_SIGN"},
	{CKF_SIGN_RECOVER, "CKF_SIGN_RECOVER"},
	{CKF_VERIFY, "CKF_VERIFY"},
	{CKF_VERIFY_RECOVER, "CKF_VERIFY_RECOVER"},
	{CKF_GENERATE, "CKF_GENERATE"},
	{CKF_GENERATE_KEY_PAIR, "CKF_GENERATE_KEY_PAIR"},
	{CKF_WRAP, "CKF_WRAP"},
	{CKF_UNWRAP, "CKF_UNWRAP"},
	{CKF_DERIVE, "CKF_DERIVE"},
	{CKF_EC_F_P, "CKF_EC_F_P"},
	{CKF_EC_F_2M, "CKF_EC_F_2M"},
	{CKF_EC_ECPARAMETERS, "CKF_EC_ECPARAMETERS"},
	{CKF_EC_NAMEDCURVE, "CKF_EC_NAMEDCURVE"},
	{CKF_EC_UNCOMPRESS, "CKF_EC_UNCOMPRESS"},
	{CKF_EC_COMPRESS, "CKF_EC_COMPRESS"},
	{CKF_EXTENSION, "CKF_EXTENSION"},
	{0, NULL}
};

struct ELEMENT CK_TOKEN_INFO_FLAG_LIST[] =
{
	{CKF_RNG, "CKF_RNG"},
	{CKF_WRITE_PROTECTED, "CKF_WRITE_PROTECTED"},
	{CKF_LOGIN_REQUIRED, "CKF_LOGIN_REQUIRED"},
	{CKF_USER_PIN_INITIALIZED, "CKF_USER_PIN_INITIALIZED"},
	{CKF_RESTORE_KEY_NOT_NEEDED, "CKF_RESTORE_KEY_NOT_NEEDED"},
	{CKF_CLOCK_ON_TOKEN, "CKF_CLOCK_ON_TOKEN"},
	{CKF_PROTECTED_AUTHENTICATION_PATH, "CKF_PROTECTED_AUTHENTICATION_PATH"},
	{CKF_DUAL_CRYPTO_OPERATIONS, "CKF_DUAL_CRYPTO_OPERATIONS"},
	{CKF_TOKEN_INITIALIZED, "CKF_TOKEN_INITIALIZED"},
	{CKF_SECONDARY_AUTHENTICATION, "CKF_SECONDARY_AUTHENTICATION"},
	{CKF_USER_PIN_COUNT_LOW, "CKF_USER_PIN_COUNT_LOW"},
	{CKF_USER_PIN_FINAL_TRY, "CKF_USER_PIN_FINAL_TRY"},
	{CKF_USER_PIN_LOCKED, "CKF_USER_PIN_LOCKED"},
	{CKF_USER_PIN_TO_BE_CHANGED, "CKF_USER_PIN_TO_BE_CHANGED"},
	{CKF_SO_PIN_COUNT_LOW, "CKF_SO_PIN_COUNT_LOW"},
	{CKF_SO_PIN_FINAL_TRY, "CKF_SO_PIN_FINAL_TRY"},
	{CKF_SO_PIN_LOCKED, "CKF_SO_PIN_LOCKED"},
	{CKF_SO_PIN_TO_BE_CHANGED, "CKF_SO_PIN_TO_BE_CHANGED"},
	{0, NULL}
};

struct ELEMENT CKR_LIST[] =
{
	{CKR_OK, "CKR_OK"},
	{CKR_CANCEL, "CKR_CANCEL"},
	{CKR_HOST_MEMORY, "CKR_HOST_MEMORY"},
	{CKR_SLOT_ID_INVALID, "CKR_SLOT_ID_INVALID"},
	{CKR_GENERAL_ERROR, "CKR_GENERAL_ERROR"},
	{CKR_FUNCTION_FAILED, "CKR_FUNCTION_FAILED"},
	{CKR_ARGUMENTS_BAD, "CKR_ARGUMENTS_BAD"},
	{CKR_NO_EVENT, "CKR_NO_EVENT"},
	{CKR_NEED_TO_CREATE_THREADS, "CKR_NEED_TO_CREATE_THREADS"},
	{CKR_CANT_LOCK, "CKR_CANT_LOCK"},
	{CKR_ATTRIBUTE_READ_ONLY, "CKR_ATTRIBUTE_READ_ONLY"},
	{CKR_ATTRIBUTE_SENSITIVE, "CKR_ATTRIBUTE_SENSITIVE"},
	{CKR_ATTRIBUTE_TYPE_INVALID, "CKR_ATTRIBUTE_TYPE_INVALID"},
	{CKR_ATTRIBUTE_VALUE_INVALID, "CKR_ATTRIBUTE_VALUE_INVALID"},
	{CKR_DATA_INVALID, "CKR_DATA_INVALID"},
	{CKR_DATA_LEN_RANGE, "CKR_DATA_LEN_RANGE"},
	{CKR_DEVICE_ERROR, "CKR_DEVICE_ERROR"},
	{CKR_DEVICE_MEMORY, "CKR_DEVICE_MEMORY"},
	{CKR_DEVICE_REMOVED, "CKR_DEVICE_REMOVED"},
	{CKR_ENCRYPTED_DATA_INVALID, "CKR_ENCRYPTED_DATA_INVALID"},
	{CKR_ENCRYPTED_DATA_LEN_RANGE, "CKR_ENCRYPTED_DATA_LEN_RANGE"},
	{CKR_FUNCTION_CANCELED, "CKR_FUNCTION_CANCELED"},
	{CKR_FUNCTION_NOT_PARALLEL, "CKR_FUNCTION_NOT_PARALLEL"},
	{CKR_FUNCTION_NOT_SUPPORTED, "CKR_FUNCTION_NOT_SUPPORTED"},
	{CKR_KEY_HANDLE_INVALID, "CKR_KEY_HANDLE_INVALID"},
	{CKR_KEY_SIZE_RANGE, "CKR_KEY_SIZE_RANGE"},
	{CKR_KEY_TYPE_INCONSISTENT, "CKR_KEY_TYPE_INCONSISTENT"},
	{CKR_KEY_NOT_NEEDED, "CKR_KEY_NOT_NEEDED"},
	{CKR_KEY_CHANGED, "CKR_KEY_CHANGED"},
	{CKR_KEY_NEEDED, "CKR_KEY_NEEDED"},
	{CKR_KEY_INDIGESTIBLE, "CKR_KEY_INDIGESTIBLE"},
	{CKR_KEY_FUNCTION_NOT_PERMITTED, "CKR_KEY_FUNCTION_NOT_PERMITTED"},
	{CKR_KEY_NOT_WRAPPABLE, "CKR_KEY_NOT_WRAPPABLE"},
	{CKR_KEY_UNEXTRACTABLE, "CKR_KEY_UNEXTRACTABLE"},
	{CKR_MECHANISM_INVALID, "CKR_MECHANISM_INVALID"},
	{CKR_MECHANISM_PARAM_INVALID, "CKR_MECHANISM_PARAM_INVALID"},
	{CKR_OBJECT_HANDLE_INVALID, "CKR_OBJECT_HANDLE_INVALID"},
	{CKR_OPERATION_ACTIVE, "CKR_OPERATION_ACTIVE"},
	{CKR_OPERATION_NOT_INITIALIZED, "CKR_OPERATION_NOT_INITIALIZED"},
	{CKR_PIN_INCORRECT, "CKR_PIN_INCORRECT"},
	{CKR_PIN_INVALID, "CKR_PIN_INVALID"},
	{CKR_PIN_LEN_RANGE, "CKR_PIN_LEN_RANGE"},
	{CKR_PIN_EXPIRED, "CKR_PIN_EXPIRED"},
	{CKR_PIN_LOCKED, "CKR_PIN_LOCKED"},
	{CKR_SESSION_CLOSED, "CKR_SESSION_CLOSED"},
	{CKR_SESSION_COUNT, "CKR_SESSION_COUNT"},
	{CKR_SESSION_HANDLE_INVALID, "CKR_SESSION_HANDLE_INVALID"},
	{CKR_SESSION_PARALLEL_NOT_SUPPORTED, "CKR_SESSION_PARALLEL_NOT_SUPPORTED"},
	{CKR_SESSION_READ_ONLY, "CKR_SESSION_READ_ONLY"},
	{CKR_SESSION_EXISTS, "CKR_SESSION_EXISTS"},
	{CKR_SESSION_READ_ONLY_EXISTS, "CKR_SESSION_READ_ONLY_EXISTS"},
	{CKR_SESSION_READ_WRITE_SO_EXISTS, "CKR_SESSION_READ_WRITE_SO_EXISTS"},
	{CKR_SIGNATURE_INVALID, "CKR_SIGNATURE_INVALID"},
	{CKR_SIGNATURE_LEN_RANGE, "CKR_SIGNATURE_LEN_RANGE"},
	{CKR_TEMPLATE_INCOMPLETE, "CKR_TEMPLATE_INCOMPLETE"},
	{CKR_TEMPLATE_INCONSISTENT, "CKR_TEMPLATE_INCONSISTENT"},
	{CKR_TOKEN_NOT_PRESENT, "CKR_TOKEN_NOT_PRESENT"},
	{CKR_TOKEN_NOT_RECOGNIZED, "CKR_TOKEN_NOT_RECOGNIZED"},
	{CKR_TOKEN_WRITE_PROTECTED, "CKR_TOKEN_WRITE_PROTECTED"},
	{CKR_UNWRAPPING_KEY_HANDLE_INVALID, "CKR_UNWRAPPING_KEY_HANDLE_INVALID"},
	{CKR_UNWRAPPING_KEY_SIZE_RANGE, "CKR_UNWRAPPING_KEY_SIZE_RANGE"},
	{CKR_UNWRAPPING_KEY_TYPE_INCONSISTENT, "CKR_UNWRAPPING_KEY_TYPE_INCONSISTENT"},
	{CKR_USER_ALREADY_LOGGED_IN, "CKR_USER_ALREADY_LOGGED_IN"},
	{CKR_USER_NOT_LOGGED_IN, "CKR_USER_NOT_LOGGED_IN"},
	{CKR_USER_PIN_NOT_INITIALIZED, "CKR_USER_PIN_NOT_INITIALIZED"},
	{CKR_USER_TYPE_INVALID, "CKR_USER_TYPE_INVALID"},
	{CKR_USER_ANOTHER_ALREADY_LOGGED_IN, "CKR_USER_ANOTHER_ALREADY_LOGGED_IN"},
	{CKR_USER_TOO_MANY_TYPES, "CKR_USER_TOO_MANY_TYPES"},
	{CKR_WRAPPED_KEY_INVALID, "CKR_WRAPPED_KEY_INVALID"},
	{CKR_WRAPPED_KEY_LEN_RANGE, "CKR_WRAPPED_KEY_LEN_RANGE"},
	{CKR_WRAPPING_KEY_HANDLE_INVALID, "CKR_WRAPPING_KEY_HANDLE_INVALID"},
	{CKR_WRAPPING_KEY_SIZE_RANGE, "CKR_WRAPPING_KEY_SIZE_RANGE"},
	{CKR_WRAPPING_KEY_TYPE_INCONSISTENT, "CKR_WRAPPING_KEY_TYPE_INCONSISTENT"},
	{CKR_RANDOM_SEED_NOT_SUPPORTED, "CKR_RANDOM_SEED_NOT_SUPPORTED"},
	{CKR_RANDOM_NO_RNG, "CKR_RANDOM_NO_RNG"},
	{CKR_DOMAIN_PARAMS_INVALID, "CKR_DOMAIN_PARAMS_INVALID"},
	{CKR_BUFFER_TOO_SMALL, "CKR_BUFFER_TOO_SMALL"},
	{CKR_SAVED_STATE_INVALID, "CKR_SAVED_STATE_INVALID"},
	{CKR_INFORMATION_SENSITIVE, "CKR_INFORMATION_SENSITIVE"},
	{CKR_STATE_UNSAVEABLE, "CKR_STATE_UNSAVEABLE"},
	{CKR_CRYPTOKI_NOT_INITIALIZED, "CKR_CRYPTOKI_NOT_INITIALIZED"},
	{CKR_CRYPTOKI_ALREADY_INITIALIZED, "CKR_CRYPTOKI_ALREADY_INITIALIZED"},
	{CKR_MUTEX_BAD, "CKR_MUTEX_BAD"},
	{CKR_MUTEX_NOT_LOCKED, "CKR_MUTEX_NOT_LOCKED"},
	{CKR_NEW_PIN_MODE, "CKR_NEW_PIN_MODE"},
	{CKR_NEXT_OTP, "CKR_NEXT_OTP"},
	{CKR_FUNCTION_REJECTED, "CKR_FUNCTION_REJECTED"},
	{CKR_VENDOR_DEFINED, "CKR_VENDOR_DEFINED"},
	{0, NULL}
};

struct FUNCTIONINFO
{
	int impl;
	char *funcName;
};

struct FUNCTIONINFO FUNCTIONINFO_LIST[] = 
{
	{0, "C_Initialize"},
	{0, "C_Finalize"},
	{0, "C_GetInfo"},
	{0, "C_GetFunctionList"},
	{0, "C_GetSlotList"},
	{0, "C_GetSlotInfo"},
	{0, "C_GetTokenInfo"},
	{0, "C_GetMechanismList"},
	{0, "C_GetMechanismInfo"},
	{0, "C_InitToken"},
	{0, "C_InitPIN"},
	{0, "C_SetPIN"},
	{0, "C_OpenSession"},
	{0, "C_CloseSession"},
	{0, "C_CloseAllSessions"},
	{0, "C_GetSessionInfo"},
	{0, "C_GetOperationState"},
	{0, "C_SetOperationState"},
	{0, "C_Login"},
	{0, "C_Logout"},
	{0, "C_CreateObject"},
	{0, "C_CopyObject"},
	{0, "C_DestroyObject"},
	{0, "C_GetObjectSize"},
	{0, "C_GetAttributeValue"},
	{0, "C_SetAttributeValue"},
	{0, "C_FindObjectsInit"},
	{0, "C_FindObjects"},
	{0, "C_FindObjectsFinal"},
	{0, "C_EncryptInit"},
	{0, "C_Encrypt"},
	{0, "C_EncryptUpdate"},
	{0, "C_EncryptFinal"},
	{0, "C_DecryptInit"},
	{0, "C_Decrypt"},
	{0, "C_DecryptUpdate"},
	{0, "C_DecryptFinal"},
	{0, "C_DigestInit"},
	{0, "C_Digest"},
	{0, "C_DigestUpdate"},
	{0, "C_DigestKey"},
	{0, "C_DigestFinal"},
	{0, "C_SignInit"},
	{0, "C_Sign"},
	{0, "C_SignUpdate"},
	{0, "C_SignFinal"},
	{0, "C_SignRecoverInit"},
	{0, "C_SignRecover"},
	{0, "C_VerifyInit"},
	{0, "C_Verify"},
	{0, "C_VerifyUpdate"},
	{0, "C_VerifyFinal"},
	{0, "C_VerifyRecoverInit"},
	{0, "C_VerifyRecover"},
	{0, "C_DigestEncryptUpdate"},
	{0, "C_DecryptDigestUpdate"},
	{0, "C_SignEncryptUpdate"},
	{0, "C_DecryptVerifyUpdate"},
	{0, "C_GenerateKey"},
	{0, "C_GenerateKeyPair"},
	{0, "C_WrapKey"},
	{0, "C_UnwrapKey"},
	{0, "C_DeriveKey"},
	{0, "C_SeedRandom"},
	{0, "C_GenerateRandom"},
	{0, "C_GetFunctionStatus"},
	{0, "C_CancelFunction"},
	{0, "C_WaitForSlotEvent"},
	{0, NULL}
};

int printFlags(CK_FLAGS flags, struct ELEMENT *list)
{
	int j = 0;
	while((list[j].eleValue!=0) & (list[j].eleName != NULL))
	{
		if((list[j].eleValue & flags) == list[j].eleValue) //bitmask match
		{
			printf("%s, ", list[j].eleName);
		}
		j++;
	}
	
	
	printf("\n");
	return 0;
}

int
searchEleName(CK_ULONG value,  struct ELEMENT *list, int listLength)
{
	int j;
	for(j = 0; j < listLength; j++)
	{
		if(list[j].eleValue == value) return j;
	}
	return -1;
}

int
returnValuePrinting(const char callingFunction[], CK_RV rv)
{
	if(!sArguments.verbose)
	{
		printf("\n");
		return 0;
	}
	
	int k;
	k = searchEleName(rv, CKR_LIST, (sizeof(CKR_LIST)/sizeof(*CKR_LIST)));
	if(k != -1)
	{
		printf("%s: %s\n", callingFunction, CKR_LIST[k].eleName);
	}
	else
	{
		printf("%s: Unknown return value: %lu\n", callingFunction, rv);
	}

	return 0;
}

int
setFunctionImplemented(const char functionName[])
{
	int j = 0;
	while(FUNCTIONINFO_LIST[j].funcName != NULL)
	{
		if(!strcmp(functionName, FUNCTIONINFO_LIST[j].funcName))
		{
			FUNCTIONINFO_LIST[j].impl = 1;
			return 0;
		}
		j++;
	}
	return 1;
}

int
checkFunctionImplemented(const char functionName[])
{
	int j = 0;
	while(FUNCTIONINFO_LIST[j].funcName != NULL)
	{
		if(!strcmp(functionName, FUNCTIONINFO_LIST[j].funcName))
		{
			return FUNCTIONINFO_LIST[j].impl;
		}
		j++;
	}
	return -1;
}

int
checkDependecies( const char *dep[])
{
	int rv = 0;
	int j = 0;
	while(dep[j] != NULL)
	{
		rv = checkFunctionImplemented(dep[j]);
		if(rv != 1) 
		{
			printf("  MISSING: %s\n", dep[j]);
			return -1;
		}
		j++;
	}
	return 1;
}
